### ISSUE TITLE
Pls add readme.md

### ISSUE THREAD

**Issue by JavaNeed** [nfrankel/microservice-sample#1]
Hello Sir,

Could you please add readme.md ? So that your follower will understand how to execute the program..

**Comment by nfrankel** [comment]
* <https://blog.frankel.ch/going-the-microservices-way-part-1/>
* <https://blog.frankel.ch/going-the-microservices-way-part-2/>
* <https://blog.frankel.ch/going-the-microservices-way-part-3/>
